name = "portfolio-starting-page"
main = "worker.js"
compatibility_date = "2024-09-23"

routes = [
  { pattern = "portfolio.sevynidd.org/*", zone_name = "sevynidd.org" }
]

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true
